//! advanced_sor.rs
//! ================
//! Advanced Smart Order Router (SOR) implementation.
//! Intelligently splits large parent orders into multiple child orders
//! across different limit price levels to minimize market impact and
//! hide liquidity intentions.
//!
//! Optimized for AMD Ryzen AI 5 with microsecond-level execution.

use std::sync::Arc;
use std::time::{Duration, Instant};
use parking_lot::RwLock;
use log::{info, debug, warn};

/// Order side enumeration
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OrderSide {
    Buy,
    Sell,
}

/// Order type for SOR
#[derive(Debug, Clone)]
pub struct ParentOrder {
    pub order_id: String,
    pub symbol: String,
    pub side: OrderSide,
    pub total_quantity: f64,
    pub filled_quantity: f64,
    pub limit_price: Option<f64>,
    pub is_aggressive: bool,
    pub created_at: Instant,
}

impl ParentOrder {
    pub fn remaining_qty(&self) -> f64 {
        self.total_quantity - self.filled_quantity
    }

    pub fn is_complete(&self) -> bool {
        self.remaining_qty() <= 0.0
    }
}

/// Child order generated by SOR
#[derive(Debug, Clone)]
pub struct ChildOrder {
    pub child_id: String,
    pub parent_order_id: String,
    pub symbol: String,
    pub side: OrderSide,
    pub quantity: f64,
    pub price: f64,
    pub order_type: ChildOrderType,
    pub status: ChildOrderStatus,
    pub filled_qty: f64,
    pub created_at: Instant,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChildOrderType {
    Limit,
    Market,
    PostOnly,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChildOrderStatus {
    Pending,
    Submitted,
    PartiallyFilled,
    Filled,
    Cancelled,
    Rejected,
}

/// Level in the order book for splitting
#[derive(Debug, Clone)]
pub struct PriceLevel {
    pub price: f64,
    pub quantity: f64,
    pub priority: u8, // Higher = more preferred
}

/// Smart Order Router configuration
#[derive(Debug, Clone)]
pub struct SorConfig {
    /// Maximum percentage of order book depth to take per child
    pub max_depth_ratio: f64,
    /// Minimum child order size
    pub min_child_qty: f64,
    /// Maximum number of child orders per parent
    pub max_children: usize,
    /// Price improvement ticks for limit orders
    pub price_improvement_ticks: u8,
    /// Aggressiveness level (0-10): higher = more aggressive
    pub aggressiveness: u8,
    /// Time horizon for execution in milliseconds
    pub time_horizon_ms: u64,
}

impl Default for SorConfig {
    fn default() -> Self {
        Self {
            max_depth_ratio: 0.1,      // Max 10% of depth per child
            min_child_qty: 0.001,      // Minimum child size
            max_children: 10,          // Max 10 children
            price_improvement_ticks: 1,
            aggressiveness: 5,         // Medium aggressiveness
            time_horizon_ms: 5000,     // 5 second horizon
        }
    }
}

/// Statistics for SOR performance tracking
#[derive(Debug, Default)]
pub struct SorStatistics {
    pub total_orders_routed: u64,
    pub total_children_created: u64,
    pub avg_children_per_order: f64,
    pub avg_execution_time_ms: f64,
    pub price_improvement_bps: f64,
    pub fill_rate: f64,
}

/// Advanced Smart Order Router
pub struct SmartOrderRouter {
    config: SorConfig,
    statistics: RwLock<SorStatistics>,
    /// Cache of recent order book depths per symbol
    order_book_cache: RwLock<std::collections::HashMap<String, Vec<PriceLevel>>>,
}

impl SmartOrderRouter {
    /// Create a new Smart Order Router
    pub fn new(config: SorConfig) -> Self {
        info!("Initializing Smart Order Router with config: {:?}", config);
        Self {
            config,
            statistics: RwLock::new(SorStatistics::default()),
            order_book_cache: RwLock::new(std::collections::HashMap::new()),
        }
    }

    /// Update order book cache for a symbol
    pub fn update_order_book(&self, symbol: String, levels: Vec<PriceLevel>) {
        let mut cache = self.order_book_cache.write();
        cache.insert(symbol, levels);
    }

    /// Split a parent order into optimized child orders
    pub fn split_order(
        &self,
        parent: &ParentOrder,
        current_mid_price: f64,
        tick_size: f64,
    ) -> Vec<ChildOrder> {
        let start_time = Instant::now();
        let remaining_qty = parent.remaining_qty();

        if remaining_qty <= 0.0 {
            return vec![];
        }

        debug!(
            "Splitting order {} | Symbol: {} | Side: {:?} | Remaining: {}",
            parent.order_id, parent.symbol, parent.side, remaining_qty
        );

        // Get order book depth for this symbol
        let order_book = {
            let cache = self.order_book_cache.read();
            cache.get(&parent.symbol).cloned().unwrap_or_default()
        };

        // Calculate optimal child orders based on strategy
        let mut children = Vec::with_capacity(self.config.max_children);

        if parent.is_aggressive || order_book.is_empty() {
            // Aggressive mode: use market orders or tight limits
            children = self.split_aggressive(parent, current_mid_price, tick_size);
        } else {
            // Passive mode: ladder orders through the book
            children = self.split_passive(parent, &order_book, current_mid_price, tick_size);
        }

        // Enforce maximum children limit
        if children.len() > self.config.max_children {
            children.truncate(self.config.max_children);
            // Redistribute quantity to truncated children
            let truncated_qty: f64 = children.iter().map(|c| c.quantity).sum();
            let leftover = remaining_qty - truncated_qty;
            if leftover > 0.0 && !children.is_empty() {
                children[0].quantity += leftover;
            }
        }

        // Update statistics
        {
            let mut stats = self.statistics.write();
            stats.total_orders_routed += 1;
            stats.total_children_created += children.len() as u64;
            stats.avg_children_per_order =
                stats.total_children_created as f64 / stats.total_orders_routed as f64;
            stats.avg_execution_time_ms = start_time.elapsed().as_secs_f64() * 1000.0;
        }

        info!(
            "Order {} split into {} children in {:.3}ms",
            parent.order_id,
            children.len(),
            start_time.elapsed().as_secs_f64() * 1000.0
        );

        children
    }

    /// Aggressive splitting: prioritize immediate execution
    fn split_aggressive(
        &self,
        parent: &ParentOrder,
        mid_price: f64,
        tick_size: f64,
    ) -> Vec<ChildOrder> {
        let mut children = Vec::new();
        let remaining = parent.remaining_qty();

        // Split into 2-3 aggressive chunks
        let chunk_sizes = self.calculate_chunk_sizes(remaining, 3);

        for (i, qty) in chunk_sizes.into_iter().enumerate() {
            if qty < self.config.min_child_qty {
                continue;
            }

            let price = match parent.side {
                OrderSide::Buy => {
                    // Buy above mid for aggression
                    mid_price + tick_size * (self.config.price_improvement_ticks as f64)
                }
                OrderSide::Sell => {
                    // Sell below mid for aggression
                    mid_price - tick_size * (self.config.price_improvement_ticks as f64)
                }
            };

            let child = ChildOrder {
                child_id: format!("{}_child_{}", parent.order_id, i),
                parent_order_id: parent.order_id.clone(),
                symbol: parent.symbol.clone(),
                side: parent.side,
                quantity: qty,
                price,
                order_type: if parent.is_aggressive {
                    ChildOrderType::Market
                } else {
                    ChildOrderType::Limit
                },
                status: ChildOrderStatus::Pending,
                filled_qty: 0.0,
                created_at: Instant::now(),
            };

            children.push(child);
        }

        children
    }

    /// Passive splitting: ladder through order book
    fn split_passive(
        &self,
        parent: &ParentOrder,
        order_book: &[PriceLevel],
        mid_price: f64,
        tick_size: f64,
    ) -> Vec<ChildOrder> {
        let mut children = Vec::new();
        let remaining = parent.remaining_qty();
        let mut qty_to_allocate = remaining;

        // Sort levels by priority (best first)
        let mut sorted_levels = order_book.to_vec();
        sorted_levels.sort_by_key(|l| -(l.priority as i32));

        for (i, level) in sorted_levels.iter().take(self.config.max_children).enumerate() {
            if qty_to_allocate <= 0.0 {
                break;
            }

            // Calculate quantity for this level
            // Don't take more than max_depth_ratio of available liquidity
            let max_at_level = level.quantity * self.config.max_depth_ratio;
            let qty_at_level = qty_to_allocate.min(max_at_level).max(self.config.min_child_qty);

            if qty_at_level < self.config.min_child_qty {
                continue;
            }

            // Price with slight improvement for better queue position
            let price = match parent.side {
                OrderSide::Buy => {
                    // Place slightly below ask for passive buy
                    level.price - tick_size * (self.config.price_improvement_ticks as f64 * 0.5)
                }
                OrderSide::Sell => {
                    // Place slightly above bid for passive sell
                    level.price + tick_size * (self.config.price_improvement_ticks as f64 * 0.5)
                }
            };

            let child = ChildOrder {
                child_id: format!("{}_child_{}", parent.order_id, i),
                parent_order_id: parent.order_id.clone(),
                symbol: parent.symbol.clone(),
                side: parent.side,
                quantity: qty_at_level,
                price,
                order_type: ChildOrderType::PostOnly,
                status: ChildOrderStatus::Pending,
                filled_qty: 0.0,
                created_at: Instant::now(),
            };

            children.push(child);
            qty_to_allocate -= qty_at_level;
        }

        // If we still have quantity left, add a final marketable order
        if qty_to_allocate >= self.config.min_child_qty {
            let price = match parent.side {
                OrderSide::Buy => mid_price + tick_size,
                OrderSide::Sell => mid_price - tick_size,
            };

            children.push(ChildOrder {
                child_id: format!("{}_child_final", parent.order_id),
                parent_order_id: parent.order_id.clone(),
                symbol: parent.symbol.clone(),
                side: parent.side,
                quantity: qty_to_allocate,
                price,
                order_type: ChildOrderType::Market,
                status: ChildOrderStatus::Pending,
                filled_qty: 0.0,
                created_at: Instant::now(),
            });
        }

        children
    }

    /// Calculate optimal chunk sizes for order splitting
    fn calculate_chunk_sizes(&self, total_qty: f64, num_chunks: usize) -> Vec<f64> {
        if num_chunks == 0 {
            return vec![];
        }

        let base_size = total_qty / num_chunks as f64;
        let mut sizes = Vec::with_capacity(num_chunks);

        // Use Fibonacci-like sizing: smaller first, larger later
        // This tests liquidity before committing full size
        let fib_ratios = [0.1, 0.15, 0.2, 0.25, 0.3];

        for i in 0..num_chunks {
            let ratio = fib_ratios.get(i).unwrap_or(&0.3);
            let qty = (total_qty * ratio).max(self.config.min_child_qty);
            sizes.push(qty);
        }

        // Normalize to ensure sum equals total
        let sum: f64 = sizes.iter().sum();
        if sum > 0.0 {
            for size in &mut sizes {
                *size = (*size / sum) * total_qty;
            }
        }

        sizes
    }

    /// Get current SOR statistics
    pub fn get_statistics(&self) -> SorStatistics {
        self.statistics.read().clone()
    }

    /// Update fill status for a child order
    pub fn update_child_fill(&self, child_id: &str, filled_qty: f64) {
        debug!("Child order {} filled: {}", child_id, filled_qty);
        // In production, this would update internal state tracking
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_chunk_size_calculation() {
        let sor = SmartOrderRouter::new(SorConfig::default());
        let chunks = sor.calculate_chunk_sizes(1.0, 5);
        
        assert_eq!(chunks.len(), 5);
        let sum: f64 = chunks.iter().sum();
        assert!((sum - 1.0).abs() < 0.001);
    }

    #[test]
    fn test_parent_order_remaining() {
        let order = ParentOrder {
            order_id: "test".to_string(),
            symbol: "BTCUSDT".to_string(),
            side: OrderSide::Buy,
            total_quantity: 1.0,
            filled_quantity: 0.3,
            limit_price: Some(50000.0),
            is_aggressive: false,
            created_at: Instant::now(),
        };

        assert!((order.remaining_qty() - 0.7).abs() < 0.001);
        assert!(!order.is_complete());
    }
}
