"""
gamma_scalping.py - Algorithmic Gamma Scalping Logic

STAGE 10 | CHAPTER 3 | FILE 3

This module implements algorithmic logic for gamma scalping - automatically
capturing profits from the underlying asset's volatility by dynamically 
adjusting the delta hedge while holding a long gamma options position.

Key Features:
- Automatic rebalancing based on delta drift from gamma exposure
- Profit capture from mean-reverting price movements
- Integration with delta hedger for complete risk management
- Fee-aware execution to ensure profitability

Hardware Optimization:
- Efficient state tracking with minimal memory footprint
- Vectorized backtesting support
- ROCm-ready for GPU-accelerated scenario analysis
"""

import numpy as np
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum
import time


@dataclass
class GammaScalpConfig:
    """Configuration for gamma scalping strategy."""
    # Rebalancing triggers
    delta_drift_threshold: float = 0.10  # Rebalance when delta drifts by 10% of position
    min_price_move_pct: float = 0.005  # Minimum price move to trigger scalp (0.5%)
    
    # Position sizing
    scalp_fraction: float = 0.5  # Fraction of delta to scalp off
    max_position_size: float = 100000.0  # Max position in USD
    
    # Profit targets
    profit_target_per_scalp: float = 0.002  # Target 0.2% profit per scalp
    daily_profit_target: float = 0.01  # Target 1% daily profit
    
    # Risk limits
    max_inventory_risk: float = 0.15  # Max net delta as % of portfolio
    stop_loss_per_scalp: float = 0.005  # Stop loss at 0.5% per scalp
    
    # Fees
    round_trip_fee: float = 0.001  # Total fees for round trip (0.1%)
    
    # Timing
    min_scalp_interval_ms: int = 5000  # Minimum 5 seconds between scalps
    cooldown_after_stop_ms: int = 60000  # 1 minute cooldown after stop loss


@dataclass
class ScalpSignal:
    """Signal generated by gamma scalping engine."""
    timestamp: float
    action: str  # "scalp_long", "scalp_short", "close_long", "close_short"
    quantity: float  # Quantity to trade
    entry_delta: float  # Delta at signal generation
    target_delta: float  # Target delta after scalp
    expected_profit: float
    stop_loss_price: Optional[float]
    reason: str


@dataclass
class ScalpPosition:
    """Tracks an active scalp position."""
    open_time: float
    side: str  # "long" or "short"
    quantity: float
    entry_price: float
    current_price: float
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    is_closed: bool = False
    close_time: Optional[float] = None


@dataclass
class PortfolioGammaState:
    """Current gamma exposure state."""
    total_gamma: float
    total_delta: float
    underlying_price: float
    vega_exposure: float
    theta_decay: float
    option_notional: float


class GammaScalper:
    """
    Algorithmic gamma scalping engine.
    
    Automatically captures profits from volatility by:
    1. Holding long gamma options positions
    2. Selling into price rallies (reducing long delta)
    3. Buying into price dips (increasing long delta)
    
    This creates a "scalping" effect that monetizes gamma exposure.
    """
    
    def __init__(self, config: Optional[GammaScalpConfig] = None):
        """
        Initialize the gamma scalper.
        
        Args:
            config: Scalping configuration (uses defaults if None)
        """
        self.config = config or GammaScalpConfig()
        self.active_positions: List[ScalpPosition] = []
        self.closed_positions: List[ScalpPosition] = []
        self.last_scalp_time = 0.0
        self.daily_pnl = 0.0
        self.scalp_count = 0
        self.stop_loss_count = 0
        
        # State tracking
        self._reference_delta = 0.0
        self._last_price = 0.0
        self._cumulative_scalp_pnl = 0.0
    
    def analyze_gamma_position(
        self, 
        state: PortfolioGammaState
    ) -> Optional[ScalpSignal]:
        """
        Analyze gamma position and generate scalp signal if conditions are met.
        
        Args:
            state: Current portfolio gamma state
            
        Returns:
            ScalpSignal if scalping opportunity exists, None otherwise
        """
        current_time = time.time() * 1000
        
        # Check minimum interval
        if current_time - self.last_scalp_time < self.config.min_scalp_interval_ms:
            return None
        
        # Check daily profit target (stop if reached)
        if self.daily_pnl >= self.config.daily_profit_target * state.option_notional:
            return None
        
        # Calculate delta drift due to gamma
        price_change = state.underlying_price - self._last_price
        if self._last_price == 0:
            self._last_price = state.underlying_price
            return None
        
        price_change_pct = price_change / self._last_price
        
        # Gamma causes delta to change: new_delta = old_delta + gamma * price_change
        gamma_effect = state.total_gamma * price_change
        current_delta = self._reference_delta + gamma_effect
        
        # Calculate delta drift
        delta_drift = abs(current_delta - self._reference_delta)
        delta_drift_pct = delta_drift / (state.total_gamma * state.underlying_price) if state.total_gamma != 0 else 0
        
        # Check if drift exceeds threshold
        if delta_drift_pct < self.config.delta_drift_threshold:
            return None
        
        # Check price move threshold
        if abs(price_change_pct) < self.config.min_price_move_pct:
            return None
        
        # Determine scalp direction
        if current_delta > self._reference_delta:
            # Delta increased (price went up) - sell some delta
            action = "scalp_long"
            quantity = -current_delta * self.config.scalp_fraction
            reason = f"Delta drift +{delta_drift_pct:.2%} from gamma"
        else:
            # Delta decreased (price went down) - buy some delta
            action = "scalp_short"
            quantity = -current_delta * self.config.scalp_fraction
            reason = f"Delta drift {delta_drift_pct:.2%} from gamma"
        
        # Calculate expected profit
        expected_profit = abs(quantity) * state.underlying_price * self.config.profit_target_per_scalp
        
        # Check if expected profit exceeds fees
        fees = abs(quantity) * state.underlying_price * self.config.round_trip_fee
        if expected_profit < fees * 2:  # Require 2x profit/fee ratio
            return None
        
        # Calculate stop loss price
        if action == "scalp_long":
            stop_loss = state.underlying_price * (1 + self.config.stop_loss_per_scalp)
        else:
            stop_loss = state.underlying_price * (1 - self.config.stop_loss_per_scalp)
        
        signal = ScalpSignal(
            timestamp=current_time,
            action=action,
            quantity=quantity,
            entry_delta=current_delta,
            target_delta=self._reference_delta,
            expected_profit=expected_profit,
            stop_loss_price=stop_loss,
            reason=reason
        )
        
        return signal
    
    def execute_scalp(
        self,
        signal: ScalpSignal,
        fill_price: float,
        execution_func=None
    ) -> bool:
        """
        Execute a scalp trade.
        
        Args:
            signal: Scalp signal to execute
            fill_price: Actual fill price
            execution_func: Optional function for actual execution
            
        Returns:
            True if scalp was executed successfully
        """
        if execution_func is None:
            # Just record the scalp
            self._record_scalp(signal, fill_price)
            return True
        
        try:
            side = "sell" if signal.quantity < 0 else "buy"
            execution_func(
                side=side,
                quantity=abs(signal.quantity),
                price=fill_price
            )
            
            self._record_scalp(signal, fill_price)
            return True
            
        except Exception as e:
            print(f"Scalp execution failed: {e}")
            return False
    
    def _record_scalp(self, signal: ScalpSignal, fill_price: float):
        """Record scalp execution."""
        position = ScalpPosition(
            open_time=signal.timestamp,
            side="long" if signal.action == "scalp_long" else "short",
            quantity=abs(signal.quantity),
            entry_price=fill_price,
            current_price=fill_price,
        )
        
        self.active_positions.append(position)
        self.last_scalp_time = signal.timestamp
        self.scalp_count += 1
        
        # Update reference delta
        self._reference_delta = signal.target_delta
        self._last_price = fill_price
    
    def update_positions(self, current_price: float) -> List[ScalpPosition]:
        """
        Update all active positions with current price.
        
        Returns list of positions that should be closed.
        """
        to_close = []
        
        for pos in self.active_positions:
            if pos.is_closed:
                continue
                
            pos.current_price = current_price
            
            # Calculate unrealized PnL
            if pos.side == "long":
                pos.unrealized_pnl = (current_price - pos.entry_price) * pos.quantity
            else:
                pos.unrealized_pnl = (pos.entry_price - current_price) * pos.quantity
            
            # Check profit target
            pnl_pct = pos.unrealized_pnl / (pos.entry_price * pos.quantity)
            
            if pnl_pct >= self.config.profit_target_per_scalp:
                to_close.append((pos, "profit_target"))
            elif pnl_pct <= -self.config.stop_loss_per_scalp:
                to_close.append((pos, "stop_loss"))
        
        return to_close
    
    def close_position(
        self, 
        position: ScalpPosition, 
        close_price: float,
        reason: str
    ) -> float:
        """
        Close a scalp position.
        
        Returns realized PnL.
        """
        if position.is_closed:
            return 0.0
        
        position.is_closed = True
        position.close_time = time.time() * 1000
        
        # Calculate final PnL
        if position.side == "long":
            pnl = (close_price - position.entry_price) * position.quantity
        else:
            pnl = (position.entry_price - close_price) * position.quantity
        
        # Subtract fees
        fee = position.quantity * close_price * self.config.round_trip_fee
        position.realized_pnl = pnl - fee
        
        # Update totals
        self._cumulative_scalp_pnl += position.realized_pnl
        self.daily_pnl += position.realized_pnl
        
        if reason == "stop_loss":
            self.stop_loss_count += 1
        
        # Move to closed positions
        self.active_positions.remove(position)
        self.closed_positions.append(position)
        
        return position.realized_pnl
    
    def get_statistics(self) -> Dict:
        """Get comprehensive scalping statistics."""
        if not self.closed_positions:
            return {
                "total_scalps": 0,
                "win_rate": 0.0,
                "total_pnl": 0.0,
                "avg_pnl_per_scalp": 0.0,
                "sharpe_ratio": 0.0,
            }
        
        winning_trades = [p for p in self.closed_positions if p.realized_pnl > 0]
        losing_trades = [p for p in self.closed_positions if p.realized_pnl <= 0]
        
        pnls = [p.realized_pnl for p in self.closed_positions]
        avg_pnl = np.mean(pnls)
        std_pnl = np.std(pnls) if len(pnls) > 1 else 1.0
        
        return {
            "total_scalps": len(self.closed_positions),
            "winning_trades": len(winning_trades),
            "losing_trades": len(losing_trades),
            "win_rate": len(winning_trades) / len(self.closed_positions),
            "total_pnl": self._cumulative_scalp_pnl,
            "daily_pnl": self.daily_pnl,
            "avg_pnl_per_scalp": avg_pnl,
            "sharpe_ratio": avg_pnl / std_pnl * np.sqrt(252) if std_pnl > 0 else 0,
            "stop_loss_count": self.stop_loss_count,
        }
    
    def reset_daily(self):
        """Reset daily counters."""
        self.daily_pnl = 0.0
    
    def reset_all(self):
        """Reset all state."""
        self.active_positions.clear()
        self.closed_positions.clear()
        self.last_scalp_time = 0.0
        self.daily_pnl = 0.0
        self.scalp_count = 0
        self.stop_loss_count = 0
        self._reference_delta = 0.0
        self._last_price = 0.0
        self._cumulative_scalp_pnl = 0.0


def calculate_optimal_gamma_exposure(
    implied_vol: float,
    realized_vol: float,
    theta_cost: float,
    transaction_costs: float,
) -> float:
    """
    Calculate optimal gamma exposure given market conditions.
    
    Gamma scalping is profitable when:
    - Realized vol > Implied vol (capture more than you pay)
    - Theta cost is manageable
    - Transaction costs don't eat profits
    
    Args:
        implied_vol: Market implied volatility
        realized_vol: Expected realized volatility
        theta_cost: Daily theta decay as % of position
        transaction_costs: Estimated round-trip transaction costs
        
    Returns:
        Optimal gamma exposure factor (0.0 to 1.0)
    """
    if realized_vol <= implied_vol:
        # No edge - reduce gamma
        return 0.0
    
    vol_edge = realized_vol - implied_vol
    
    # Simple heuristic: increase gamma with vol edge
    # In production, would use full optimization
    optimal = min(1.0, vol_edge / (theta_cost + transaction_costs))
    
    return max(0.0, optimal)


if __name__ == "__main__":
    # Example usage
    config = GammaScalpConfig()
    scalper = GammaScalper(config)
    
    # Simulate a long gamma position
    state = PortfolioGammaState(
        total_gamma=0.1,  # Long gamma
        total_delta=5.0,
        underlying_price=50000,
        vega_exposure=1000,
        theta_decay=-50,
        option_notional=250000,
    )
    
    # Simulate price movement
    scalper._reference_delta = 5.0
    scalper._last_price = 50000
    
    # Price goes up 2%
    state.underlying_price = 51000
    
    signal = scalper.analyze_gamma_position(state)
    
    if signal:
        print(f"Gamma Scalp Signal:")
        print(f"  Action: {signal.action}")
        print(f"  Quantity: {signal.quantity:.4f}")
        print(f"  Expected Profit: ${signal.expected_profit:.2f}")
        print(f"  Reason: {signal.reason}")
    else:
        print("No scalp opportunity")
