// core/src/microstructure/liquidity_sweeps.rs
// =============================================================================
// LIQUIDITY SWEEP & ABSORPTION DETECTION ENGINE
// =============================================================================
// Purpose: Detects institutional manipulation patterns where large market orders
// consume resting limit orders without significantly moving price (absorption),
// or aggressively sweep multiple price levels (liquidity sweep).
//
// Key Concepts:
// - Absorption: High volume, low price displacement. Indicates hidden liquidity.
// - Sweep: Rapid consumption of multiple order book levels.
// - Stop Hunt: Price spikes beyond key levels then reverses.

use std::collections::VecDeque;
use super::footprint::FootprintEngine;

/// Configuration for detection thresholds
#[derive(Debug, Clone)]
pub struct SweepConfig {
    pub volume_threshold: u64,      // Minimum volume to consider a sweep
    pub price_displacement_ticks: i64, // Max price move allowed for absorption
    pub time_window_ms: u64,        // Time window for aggregation
    pub consecutive_levels: usize,  // Min levels swept to trigger signal
}

impl Default for SweepConfig {
    fn default() -> Self {
        Self {
            volume_threshold: 100_000, // Example: 100k quote currency
            price_displacement_ticks: 5,
            time_window_ms: 100,
            consecutive_levels: 3,
        }
    }
}

/// Event types generated by the liquidity engine
#[derive(Debug, Clone)]
pub enum LiquidityEvent {
    /// Large aggressive buy/sell consuming multiple levels
    Sweep {
        timestamp_ns: u64,
        direction: bool, // true = buy, false = sell
        volume: u64,
        levels_consumed: usize,
        price_start: f64,
        price_end: f64,
    },
    /// High volume with minimal price movement (hidden liquidity)
    Absorption {
        timestamp_ns: u64,
        direction: bool,
        volume: u64,
        price: f64,
        trade_count: u32,
    },
    /// Price spiked beyond level then reversed
    StopHunt {
        timestamp_ns: u64,
        direction: bool,
        extreme_price: f64,
        reversal_price: f64,
        wick_size_ticks: i64,
    },
}

/// Sliding window trade record for time-based analysis
#[derive(Clone)]
struct TradeRecord {
    timestamp_ns: u64,
    price_tick: i64,
    quantity: u64,
    is_buyer_maker: bool,
}

/// Core Liquidity Detection Engine
pub struct LiquiditySweepDetector {
    config: SweepConfig,
    /// Circular buffer of recent trades for time-window analysis
    trade_buffer: VecDeque<TradeRecord>,
    /// Detected events queue (lock-free ready for IPC)
    events: Vec<LiquidityEvent>,
    /// Current best bid/ask in ticks
    current_bid_tick: i64,
    current_ask_tick: i64,
    /// Last detected sweep timestamp to prevent duplicates
    last_sweep_ns: u64,
}

impl LiquiditySweepDetector {
    pub fn new(config: SweepConfig) -> Self {
        Self {
            config,
            trade_buffer: VecDeque::with_capacity(1000),
            events: Vec::new(),
            current_bid_tick: 0,
            current_ask_tick: 0,
            last_sweep_ns: 0,
        }
    }

    /// Update current best bid/ask from order book
    #[inline]
    pub fn update_book(&mut self, bid: f64, ask: f64, tick_size_inv: f64) {
        self.current_bid_tick = (bid * tick_size_inv) as i64;
        self.current_ask_tick = (ask * tick_size_inv) as i64;
    }

    /// Process incoming trade and check for liquidity events
    #[inline]
    pub fn process_trade(&mut self, timestamp_ns: u64, price: f64, quantity: u64, 
                         is_buyer_maker: bool, tick_size_inv: f64) {
        let price_tick = (price * tick_size_inv) as i64;

        // Add to circular buffer
        self.trade_buffer.push_back(TradeRecord {
            timestamp_ns,
            price_tick,
            quantity,
            is_buyer_maker,
        });

        // Prune old trades outside time window
        self.prune_buffer(timestamp_ns);

        // Check for absorption (high volume, single price level)
        self.check_absorption(timestamp_ns, price_tick, quantity, is_buyer_maker, price);

        // Check for sweeps periodically (every N trades or on large volume)
        if quantity >= self.config.volume_threshold / 10 {
            self.check_sweep(timestamp_ns, tick_size_inv);
        }
    }

    fn prune_buffer(&mut self, current_ns: u64) {
        let cutoff = current_ns.saturating_sub(self.config.time_window_ms * 1_000_000);
        while let Some(front) = self.trade_buffer.front() {
            if front.timestamp_ns < cutoff {
                self.trade_buffer.pop_front();
            } else {
                break;
            }
        }
    }

    /// Detect absorption: many trades at same price with high volume
    fn check_absorption(&mut self, ts: u64, price_tick: i64, qty: u64, 
                        is_buyer_maker: bool, price_f64: f64) {
        // Count trades and volume at this exact price level in window
        let mut level_volume = 0u64;
        let mut level_count = 0u32;

        for trade in &self.trade_buffer {
            if trade.price_tick == price_tick && trade.is_buyer_maker == is_buyer_maker {
                level_volume += trade.quantity;
                level_count += 1;
            }
        }

        // Absorption criteria: high volume, many trades, but price hasn't moved much
        if level_volume >= self.config.volume_threshold && level_count >= 5 {
            // Verify price stability (simplified: check if we're still at similar level)
            let events = &mut self.events;
            events.push(LiquidityEvent::Absorption {
                timestamp_ns: ts,
                direction: !is_buyer_maker, // Aggressive buyer = !maker
                volume: level_volume,
                price: price_f64,
                trade_count: level_count,
            });
        }
    }

    /// Detect liquidity sweeps across multiple levels
    fn check_sweep(&mut self, ts: u64, tick_size_inv: f64) {
        if ts - self.last_sweep_ns < self.config.time_window_ms * 1_000_000 {
            return; // Cooldown
        }

        // Analyze buffer for directional aggression
        let mut buy_vol = 0u64;
        let mut sell_vol = 0u64;
        let mut min_tick = i64::MAX;
        let mut max_tick = i64::MIN;
        let mut first_price = 0f64;
        let mut last_price = 0f64;

        for (i, trade) in self.trade_buffer.iter().enumerate() {
            if !trade.is_buyer_maker {
                buy_vol += trade.quantity;
            } else {
                sell_vol += trade.quantity;
            }
            
            if trade.price_tick < min_tick { min_tick = trade.price_tick; }
            if trade.price_tick > max_tick { max_tick = trade.price_tick; }
            
            if i == 0 { first_price = trade.price_tick as f64 / tick_size_inv; }
            last_price = trade.price_tick as f64 / tick_size_inv;
        }

        let total_vol = buy_vol.max(sell_vol);
        let displacement = (max_tick - min_tick).abs();

        // Sweep criteria: high volume + multiple levels consumed
        if total_vol >= self.config.volume_threshold 
            && displacement >= self.config.consecutive_levels as i64 {
            
            let direction = buy_vol > sell_vol;
            self.events.push(LiquidityEvent::Sweep {
                timestamp_ns: ts,
                direction,
                volume: total_vol,
                levels_consumed: displacement as usize,
                price_start: first_price,
                price_end: last_price,
            });
            self.last_sweep_ns = ts;
        }
    }

    /// Detect stop hunts: sharp wick then reversal
    pub fn check_stop_hunt(&mut self, ts: u64, high_tick: i64, low_tick: i64, 
                           open_tick: i64, close_tick: i64, candle_time_ns: u64) {
        let wick_top = high_tick - open_tick.max(close_tick);
        let wick_bottom = open_tick.min(close_tick) - low_tick;
        
        // Significant wick threshold (e.g., 10 ticks)
        let threshold = 10; 

        if wick_top > threshold && close_tick < open_tick {
            // Long wick on top, bearish close = potential bullish stop hunt
            self.events.push(LiquidityEvent::StopHunt {
                timestamp_ns: candle_time_ns,
                direction: false, // Bullish reversal expected
                extreme_price: high_tick as f64,
                reversal_price: (close_tick as f64),
                wick_size_ticks: wick_top,
            });
        } else if wick_bottom > threshold && close_tick > open_tick {
            // Long wick on bottom, bullish close = potential bearish stop hunt
            self.events.push(LiquidityEvent::StopHunt {
                timestamp_ns: candle_time_ns,
                direction: true, // Bearish reversal expected
                extreme_price: low_tick as f64,
                reversal_price: (close_tick as f64),
                wick_size_ticks: wick_bottom,
            });
        }
    }

    /// Consume pending events (called by main loop)
    pub fn drain_events(&mut self) -> Vec<LiquidityEvent> {
        std::mem::take(&mut self.events)
    }
}
