//! Latency Probe for Tick-to-Trade Measurement
//! 
//! Measures end-to-end tick-to-trade time using rdtsc CPU cycles.
//! Logs metrics to local time-series DB via non-blocking UDP.

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};
use std::net::UdpSocket;
use std::collections::VecDeque;

use parking_lot::{Mutex, RwLock};
use serde::{Deserialize, Serialize};

/// High-precision timestamp from rdtsc
#[inline]
fn rdtsc() -> u64 {
    #[cfg(target_arch = "x86_64")]
    {
        unsafe {
            std::arch::x86_64::_rdtsc()
        }
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        // Fallback for non-x86 architectures
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos() as u64
    }
}

/// Get current time in nanoseconds
#[inline]
fn get_time_ns() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos() as u64
}

// ============================================================================
// Latency Measurement Stages
// ============================================================================

/// Trading pipeline stages for latency measurement
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PipelineStage {
    /// Market data received from exchange
    TickReceived,
    /// Order book updated
    OrderBookUpdated,
    /// Signal generated by strategy
    SignalGenerated,
    /// Risk check passed
    RiskCheckPassed,
    /// Order sent to exchange
    OrderSent,
    /// Acknowledgment received
    AckReceived,
    /// Fill confirmation
    FillConfirmed,
}

/// Single latency measurement
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LatencySample {
    /// Unique sample ID
    pub sample_id: u64,
    /// Symbol being traded
    pub symbol: String,
    /// Stage transitions
    pub stages: Vec<(PipelineStage, u64)>, // (stage, timestamp_cycles)
    /// Total tick-to-trade time in nanoseconds
    pub tick_to_trade_ns: u64,
    /// System time of sample
    pub timestamp_ns: u64,
    /// CPU core used
    pub cpu_core: Option<u32>,
}

impl LatencySample {
    pub fn new(symbol: String) -> Self {
        Self {
            sample_id: 0,
            symbol,
            stages: Vec::with_capacity(8),
            tick_to_trade_ns: 0,
            timestamp_ns: get_time_ns(),
            cpu_core: None,
        }
    }

    /// Record a stage transition
    pub fn record_stage(&mut self, stage: PipelineStage) {
        self.stages.push((stage, rdtsc()));
    }

    /// Calculate tick-to-trade latency
    pub fn calculate_tick_to_trade(&mut self) -> u64 {
        if self.stages.len() < 2 {
            return 0;
        }

        let tick_time = self.stages[0].1;
        
        // Find order sent time
        let order_sent_time = self.stages
            .iter()
            .find(|(s, _)| *s == PipelineStage::OrderSent)
            .map(|(_, t)| *t)
            .unwrap_or_else(|| self.stages.last().unwrap().1);

        // Convert cycles to nanoseconds (approximate, assuming ~3GHz CPU)
        let cycles_diff = order_sent_time - tick_time;
        self.tick_to_trade_ns = (cycles_diff as f64 * 0.33) as u64; // ~0.33 ns per cycle at 3GHz

        self.tick_to_trade_ns
    }

    /// Get latency between two specific stages
    pub fn get_stage_latency(&self, from: PipelineStage, to: PipelineStage) -> Option<u64> {
        let from_time = self.stages.iter().find(|(s, _)| *s == from)?.1;
        let to_time = self.stages.iter().find(|(s, _)| *s == to)?.1;
        
        if to_time > from_time {
            Some(((to_time - from_time) as f64 * 0.33) as u64)
        } else {
            None
        }
    }
}

// ============================================================================
// Statistics Aggregator
// ============================================================================

/// Latency statistics
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LatencyStatistics {
    /// Sample count
    pub count: u64,
    /// Minimum latency (ns)
    pub min_ns: u64,
    /// Maximum latency (ns)
    pub max_ns: u64,
    /// Mean latency (ns)
    pub mean_ns: u64,
    /// Median latency (ns)
    pub median_ns: u64,
    /// Standard deviation (ns)
    pub std_ns: u64,
    /// 50th percentile (ns)
    pub p50_ns: u64,
    /// 90th percentile (ns)
    pub p90_ns: u64,
    /// 95th percentile (ns)
    pub p95_ns: u64,
    /// 99th percentile (ns)
    pub p99_ns: u64,
    /// 99.9th percentile (ns)
    pub p999_ns: u64,
}

impl LatencyStatistics {
    /// Calculate statistics from samples
    pub fn from_samples(samples: &[u64]) -> Self {
        if samples.is_empty() {
            return Self::default();
        }

        let mut sorted = samples.to_vec();
        sorted.sort_unstable();

        let count = sorted.len() as u64;
        let sum: u64 = sorted.iter().sum();
        let mean = sum / count;

        let min = *sorted.first().unwrap();
        let max = *sorted.last().unwrap();

        // Percentiles
        let p50_idx = (count as f64 * 0.50) as usize;
        let p90_idx = (count as f64 * 0.90) as usize;
        let p95_idx = (count as f64 * 0.95) as usize;
        let p99_idx = (count as f64 * 0.99) as usize;
        let p999_idx = (count as f64 * 0.999) as usize;

        let median = sorted[p50_idx.min(sorted.len() - 1)];
        let p90 = sorted[p90_idx.min(sorted.len() - 1)];
        let p95 = sorted[p95_idx.min(sorted.len() - 1)];
        let p99 = sorted[p99_idx.min(sorted.len() - 1)];
        let p999 = sorted[p999_idx.min(sorted.len() - 1)];

        // Standard deviation
        let variance = sorted.iter()
            .map(|&x| (x as i64 - mean as i64).pow(2) as u64)
            .sum::<u64>() / count;
        let std = (variance as f64).sqrt() as u64;

        Self {
            count,
            min_ns: min,
            max_ns: max,
            mean_ns: mean,
            median_ns: median,
            std_ns: std,
            p50_ns: median,
            p90_ns: p90,
            p95_ns: p95,
            p99_ns: p99,
            p999_ns: p999,
        }
    }
}

// ============================================================================
// UDP Metrics Sender
// ============================================================================

/// Non-blocking UDP sender for metrics
pub struct UdpMetricsSender {
    socket: UdpSocket,
    target_addr: String,
    buffer: Mutex<VecDeque<String>>,
    max_buffer_size: usize,
    dropped_count: AtomicU64,
}

impl UdpMetricsSender {
    pub fn new(target_addr: &str, bind_addr: &str) -> Result<Self, std::io::Error> {
        let socket = UdpSocket::bind(bind_addr)?;
        socket.set_nonblocking(true)?;
        
        Ok(Self {
            socket,
            target_addr: target_addr.to_string(),
            buffer: Mutex::new(VecDeque::with_capacity(1000)),
            max_buffer_size: 10000,
            dropped_count: AtomicU64::new(0),
        })
    }

    /// Queue a metric for sending
    pub fn send(&self, metric: String) {
        let mut buffer = self.buffer.lock();
        
        if buffer.len() >= self.max_buffer_size {
            // Drop oldest if buffer full
            buffer.pop_front();
            self.dropped_count.fetch_add(1, Ordering::Relaxed);
        }
        
        buffer.push_back(metric);
    }

    /// Flush buffered metrics (call periodically)
    pub fn flush(&self) -> usize {
        let mut buffer = self.buffer.lock();
        let mut sent = 0;

        while let Some(metric) = buffer.pop_front() {
            match self.socket.send_to(metric.as_bytes(), &self.target_addr) {
                Ok(_) => sent += 1,
                Err(ref e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                    // Socket not ready, put back and stop
                    buffer.push_front(metric);
                    break;
                }
                Err(_) => {
                    self.dropped_count.fetch_add(1, Ordering::Relaxed);
                }
            }
        }

        sent
    }

    /// Get dropped count
    pub fn dropped_count(&self) -> u64 {
        self.dropped_count.load(Ordering::Relaxed)
    }
}

// ============================================================================
// Main Latency Probe
// ============================================================================

/// Main latency probe for tick-to-trade measurement
pub struct LatencyProbe {
    /// Current active measurements
    active_samples: RwLock<Vec<Arc<Mutex<LatencySample>>>>,
    /// Completed samples for statistics
    completed_samples: Mutex<Vec<u64>>, // Store just latencies for efficiency
    /// Sample counter
    sample_counter: AtomicU64,
    /// UDP sender
    udp_sender: Option<UdpMetricsSender>,
    /// Statistics by symbol
    stats_by_symbol: RwLock<std::collections::HashMap<String, LatencyStatistics>>,
    /// Alert thresholds (nanoseconds)
    alert_threshold_p99: AtomicU64,
    alert_threshold_mean: AtomicU64,
    /// Alerts triggered
    alerts_triggered: AtomicU64,
}

impl LatencyProbe {
    pub fn new(udp_target: Option<&str>) -> Result<Self, std::io::Error> {
        let udp_sender = if let Some(target) = udp_target {
            Some(UdpMetricsSender::new(target, "127.0.0.1:0")?)
        } else {
            None
        };

        Ok(Self {
            active_samples: RwLock::new(Vec::new()),
            completed_samples: Mutex::new(Vec::new()),
            sample_counter: AtomicU64::new(0),
            udp_sender,
            stats_by_symbol: RwLock::new(std::collections::HashMap::new()),
            alert_threshold_p99: AtomicU64::new(1_000_000), // 1ms default
            alert_threshold_mean: AtomicU64::new(100_000),   // 100μs default
            alerts_triggered: AtomicU64::new(0),
        })
    }

    /// Start measuring a new tick-to-trade cycle
    pub fn start_measurement(&self, symbol: String) -> Arc<Mutex<LatencySample>> {
        let mut sample = LatencySample::new(symbol);
        sample.sample_id = self.sample_counter.fetch_add(1, Ordering::Relaxed);
        sample.record_stage(PipelineStage::TickReceived);

        #[cfg(target_arch = "x86_64")]
        {
            sample.cpu_core = Some(unsafe {
                std::arch::x86_64::__readgsdword(0x18) as u32 // TPR on Windows
            });
        }

        let sample_arc = Arc::new(Mutex::new(sample));
        self.active_samples.write().push(sample_arc.clone());
        sample_arc
    }

    /// Complete a measurement and record statistics
    pub fn complete_measurement(&self, sample_arc: &Arc<Mutex<LatencySample>>) {
        let mut sample = sample_arc.lock();
        let latency = sample.calculate_tick_to_trade();
        let symbol = sample.symbol.clone();
        
        // Send via UDP if configured
        if let Some(ref sender) = self.udp_sender {
            let json = serde_json::json!({
                "type": "latency_sample",
                "sample_id": sample.sample_id,
                "symbol": symbol,
                "tick_to_trade_ns": latency,
                "timestamp": sample.timestamp_ns,
            });
            sender.send(json.to_string());
        }

        // Store completed sample
        drop(sample); // Release lock before acquiring others
        
        self.completed_samples.lock().push(latency);

        // Update per-symbol statistics
        let mut stats_map = self.stats_by_symbol.write();
        let samples: Vec<u64> = self.completed_samples.lock().clone();
        let stats = LatencyStatistics::from_samples(&samples);
        stats_map.insert(symbol, stats);

        // Check thresholds
        self.check_thresholds(&stats);

        // Limit stored samples
        let mut completed = self.completed_samples.lock();
        if completed.len() > 10000 {
            *completed = completed.split_off(completed.len() - 10000);
        }

        // Remove from active
        self.active_samples.write().retain(|s| !Arc::ptr_eq(s, sample_arc));
    }

    /// Check alert thresholds
    fn check_thresholds(&self, stats: &LatencyStatistics) {
        let threshold_p99 = self.alert_threshold_p99.load(Ordering::Relaxed);
        let threshold_mean = self.alert_threshold_mean.load(Ordering::Relaxed);

        if stats.p99_ns > threshold_p99 || stats.mean_ns > threshold_mean {
            self.alerts_triggered.fetch_add(1, Ordering::Relaxed);

            // Log alert via UDP
            if let Some(ref sender) = self.udp_sender {
                let json = serde_json::json!({
                    "type": "latency_alert",
                    "p99_ns": stats.p99_ns,
                    "mean_ns": stats.mean_ns,
                    "threshold_p99": threshold_p99,
                    "threshold_mean": threshold_mean,
                    "timestamp": get_time_ns(),
                });
                sender.send(json.to_string());
            }

            eprintln!(
                "LATENCY ALERT: p99={}ns (threshold={}), mean={}ns (threshold={})",
                stats.p99_ns, threshold_p99, stats.mean_ns, threshold_mean
            );
        }
    }

    /// Set alert thresholds
    pub fn set_thresholds(&self, p99_ns: u64, mean_ns: u64) {
        self.alert_threshold_p99.store(p99_ns, Ordering::Relaxed);
        self.alert_threshold_mean.store(mean_ns, Ordering::Relaxed);
    }

    /// Get current statistics for a symbol
    pub fn get_statistics(&self, symbol: &str) -> Option<LatencyStatistics> {
        self.stats_by_symbol.read().get(symbol).cloned()
    }

    /// Get overall statistics
    pub fn get_overall_statistics(&self) -> LatencyStatistics {
        let samples = self.completed_samples.lock();
        LatencyStatistics::from_samples(&samples)
    }

    /// Flush UDP buffer
    pub fn flush_udp(&self) -> usize {
        self.udp_sender.as_ref().map(|s| s.flush()).unwrap_or(0)
    }

    /// Get number of active measurements
    pub fn active_count(&self) -> usize {
        self.active_samples.read().len()
    }

    /// Get alerts triggered count
    pub fn alerts_count(&self) -> u64 {
        self.alerts_triggered.load(Ordering::Relaxed)
    }

    /// Export statistics as JSON string
    pub fn export_json(&self) -> String {
        let overall = self.get_overall_statistics();
        let stats_map = self.stats_by_symbol.read();

        let json = serde_json::json!({
            "overall": overall,
            "by_symbol": *stats_map,
            "active_count": self.active_count(),
            "alerts_triggered": self.alerts_count(),
            "timestamp": get_time_ns(),
        });

        serde_json::to_string(&json).unwrap_or_default()
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_latency_sample() {
        let mut sample = LatencySample::new("BTCUSD".to_string());
        
        sample.record_stage(PipelineStage::TickReceived);
        std::thread::sleep(Duration::from_micros(10));
        sample.record_stage(PipelineStage::SignalGenerated);
        std::thread::sleep(Duration::from_micros(10));
        sample.record_stage(PipelineStage::OrderSent);

        let latency = sample.calculate_tick_to_trade();
        
        assert!(latency > 0);
        println!("Measured latency: {}ns", latency);
    }

    #[test]
    fn test_statistics_calculation() {
        let samples = vec![100, 200, 150, 300, 250, 175, 225, 125, 275, 190];
        let stats = LatencyStatistics::from_samples(&samples);

        assert_eq!(stats.count, 10);
        assert!(stats.min_ns <= stats.max_ns);
        assert!(stats.p50_ns <= stats.p99_ns);
        println!("Stats: {:?}", stats);
    }

    #[test]
    fn test_probe_basic() {
        let probe = LatencyProbe::new(None).unwrap();
        
        let sample = probe.start_measurement("ETHUSD".to_string());
        
        {
            let mut s = sample.lock();
            s.record_stage(PipelineStage::OrderBookUpdated);
            s.record_stage(PipelineStage::RiskCheckPassed);
            s.record_stage(PipelineStage::OrderSent);
        }

        probe.complete_measurement(&sample);

        let stats = probe.get_overall_statistics();
        assert!(stats.count > 0);
        println!("Overall stats: {:?}", stats);
    }
}
